### ISSUE TITLE
AdGem Unity SDK freeze after close offer wall page

### ISSUE THREAD

**Issue by ctykaya** [AdGem/Android-Example#14] opened 2021-08-13 10:45 UTC
We are trying to integrate Unity SDK to our game. When user clicked the offerwall we are checking offerWallReady like this.
When user close the page HandleOfferwallClosed does not triggered. The the view freezed and cannot interacte with any thing. Can anyone help ? 
```
//Splash View 
 private void Awake()
    {
        AdGem.startSession(11704, false, false, true);
        AdGem.loadOfferWallBeforeShowing = true;
    }
//Game View
private void Start()
    {
        DontDestroyOnLoad(this);
        if (instance == null)
        {
            instance = this;
            try
            {
                Advertisement.AddListener(this);
                Advertisement.Initialize(gameId, false);
                //For Offerwall
                AdGem.player_id = FirebaseAuth.DefaultInstance.CurrentUser.UserId;
                
            }
            catch (System.Exception ex)
            {
                Debug.Log(ex.GetBaseException().Message);
                Crashlytics.Log(ex.GetBaseException().Message);
            }

        }
        else
            Destroy(gameObject);

    }
  void OnEnable()
    {
        AdGem.offerWallClosed += HandleOfferwallClosed;
        AdGem.offerWallRewardReceived += HandleOfferwallRewardReceived;
    }

    void OnDisable()
    {
        AdGem.offerWallClosed -= HandleOfferwallClosed;
        AdGem.offerWallRewardReceived -= HandleOfferwallRewardReceived;
    }

    private void HandleOfferwallClosed()
    {
        Debug.Log("AdGemOfferwallManager: OfferWall was closed");
    }
   public void ShowAdGemOffeWall() {

        if (AdGem.offerWallReady)
        {
            AdGem.showOfferWall();
        }
        else {
            Debug.Log("offerWallReady: false");
            PopUp.instance.ShowFail("No Offer Wall available now. Try again later", null);
        }
    }
```

**Comment by nhaynes** [comment] 2021-08-13 17:13
Hi @ctykaya, sorry you are having issues integrating with our Unity SDK.  

Could you provide the following details?

- Which version of Unity are you using?
- Which version of the SDK are you using?
- Are you running into the issue on Android, iOS or both?

**Comment by ctykaya** [comment] 2021-08-14 10:16
Hi @nhaynes
Sure here is the details
1. We are using Unity 2023.3.15f2 
2. AdGem SDK is 2.0.3
3. We are publishing only Android platform.

**Comment by ctykaya** [comment] 2021-08-17 10:59
Any solutions ? @nhaynes

**Comment by nhaynes** [comment] 2021-08-17 14:59
@ctykaya we are still looking into this.

**Comment by nhaynes** [comment] 2021-08-24 16:23
@ctykaya we have reproduced the issue and discovered its due to a dependency we are using. We are working with the vendor of this dependency to resolve the issue.

**Comment by ctykaya** [comment] 2021-08-24 18:40
Ok @nhaynes Thanks. We are tracking the issue.

**Comment by ctykaya** [comment] 2021-10-04 19:19
Any solutions? @nhaynes

**Comment by nhaynes** [comment] 2021-10-04 21:31
@ctykaya We have figured out the issue and our working on getting a new version of the Unity SDK released with it fixed but have run into some delays on getting that new version out. I will update this ticket as soon as it's available.

**Closed** 2022-10-12 19:47 UTC
