### ISSUE TITLE
AdGem is not ready to show offer wall

### ISSUE THREAD

**Issue by isamotiuc** [AdGem/Android-Example#5] opened 2018-12-11 14:24 UTC
On version `1.0.6` and `1.0.7` we have a strange bug. 
We till now didnt find steз to reproduce, but the problem is that in some cases on call `adGem.showOfferWall` we receive in logs:
`E/AdGem: AdGem is not ready to show offer wall` and nothing happens or displays. 
We can tap multiple times, and always will receive this in logs. The only solution to solve this is to restart app. But this can happen again. 
If we will find STR will report it here.

**Comment by Exaper** [comment] 2018-12-11 15:00
@isamotiuc this is expected behavior. AdGem needs to cache offer wall before showing it. Otherwise user may visit a blank (or partially loaded) screen. Prior to calling adGem.showOfferWall() it's best to ensure that the offer wall it ready via adGem.isOfferWallReady(). Your game must account for AdGem not being able to display the offer wall due to poor network conditions, server being unreachable, adblocker/proxy installed, etc. 

You mention that the Offer Wall never finishes loading. Can you log and paste here a sequence of callbacks received from adgem.registerCallback() along with device model and OS version?

**Comment by isamotiuc** [comment] 2018-12-11 15:11
@Exaper Yes the main problem is that it never finishes loading. I can reconnect internet, call ` adGem.showOfferWall()` many times, during a huge amount of time but I will always receive 
`AdGem is not ready to show offer wall`, looks like it blocks in some condition and never goes out. Helps only completely restarting application. 

So first time when application starts no problems to access AdGem, it opens instantly, but after some amount of times this bug happens, and not only on one device. 
Still trying to find steps to reproduce. 
May be this somehow relates to token live, just guesses, you now better all system.

**Comment by Exaper** [comment] 2018-12-11 15:21
@isamotiuc thanks for clarifying details for us. Please log callbacks from adgem to help us debug this issue. What is the OS version and model of device(s) you are running on?

**Comment by isamotiuc** [comment] 2018-12-11 15:34
@Exaper This was reproduced on:

- Samsung S7 android 6.0.1, 
- Samsung G3 android 5.1.1, 
- Xiaomi MI 6 android 8.0.0, 
- Xiaomi A2 android 8.1.

But I think this is not related to device.
Change logs will provide as soon as reproduce.

Thank you 👍

**Comment by isamotiuc** [comment] 2018-12-12 07:49
@Exaper Hello, I just had again this bug, this what I received in logs
![image](https://user-images.githubusercontent.com/2742322/49854147-f8ec9500-fdf1-11e8-8888-3505305595b2.png)
All this `AdGem is not ready...` messages is calls of `showOfferWall()`
As I understood it stops on `STATE_DOWNLOADING`. 
The question is, if for some reasons, for example internet issues, AdGem cant download offer wall, it will not tries again on next call `showOfferWall()`? 
For now seems like this is the issue.

If you need additional information feel free to ask

**Comment by Exaper** [comment] 2019-01-07 16:48
Fixed in v1.1.2

**Closed by Exaper** 2019-01-07 16:48 UTC
